# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_InterpCoeff <- function(n, nprime, offs, rtn) {
    .Call('_alignment_C_InterpCoeff', PACKAGE = 'alignment', n, nprime, offs, rtn)
}

C_cow <- function(Ta, X, Seg, Slack, Options) {
    .Call('_alignment_C_cow', PACKAGE = 'alignment', Ta, X, Seg, Slack, Options)
}

C_histc <- function(values, edges) {
    .Call('_alignment_C_histc', PACKAGE = 'alignment', values, edges)
}

C_ylagxCOR <- function(x, y) {
    .Call('_alignment_C_ylagxCOR', PACKAGE = 'alignment', x, y)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_alignment_RcppExport_registerCCallable', PACKAGE = 'alignment')
})
