# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_InterpCoeff <- function(n, nprime, offs, rtn) {
    .Call('_alignment_c_InterpCoeff', PACKAGE = 'alignment', n, nprime, offs, rtn)
}

c_cow <- function(Ta, X, Seg, Slack, Options) {
    .Call('_alignment_c_cow', PACKAGE = 'alignment', Ta, X, Seg, Slack, Options)
}

c_cow2 <- function(Ta, X, Seg, Slack, Options) {
    .Call('_alignment_c_cow2', PACKAGE = 'alignment', Ta, X, Seg, Slack, Options)
}

c_cow3 <- function(Ta, X, Seg, Slack, Options) {
    .Call('_alignment_c_cow3', PACKAGE = 'alignment', Ta, X, Seg, Slack, Options)
}

c_histc <- function(values, edges) {
    .Call('_alignment_c_histc', PACKAGE = 'alignment', values, edges)
}

c_ylagxCOR <- function(x, y) {
    .Call('_alignment_c_ylagxCOR', PACKAGE = 'alignment', x, y)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_alignment_RcppExport_registerCCallable', PACKAGE = 'alignment')
})
